rom_config: '../../../orig/YR9K00/config.yaml'
build_path: '../../../build/YR9K00'
delinks_path: '../../../build/YR9K00/delinks'
main_module:
  name: main
  object: '../../../build/YR9K00/build/arm9.bin'
  hash: df7b7d2b4d779aa1
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../../build/YR9K00/build/itcm.bin'
  hash: ad56253867d282ba
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../../build/YR9K00/build/dtcm.bin'
  hash: '146ae500bc37c77e'
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: '../../../build/YR9K00/build/arm9_ov000.bin'
  hash: e0f21a1e5317f87b
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: '../../../build/YR9K00/build/arm9_ov001.bin'
  hash: d162858817af7d0e
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: '../../../build/YR9K00/build/arm9_ov002.bin'
  hash: '6dad602be9743a23'
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: '../../../build/YR9K00/build/arm9_ov003.bin'
  hash: '9b416e20c51b9d06'
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: '../../../build/YR9K00/build/arm9_ov004.bin'
  hash: '50b68bbdc6c861d5'
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: '../../../build/YR9K00/build/arm9_ov005.bin'
  hash: '22c00fbace80013d'
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: '../../../build/YR9K00/build/arm9_ov006.bin'
  hash: '8d3241071b051fc3'
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: '../../../build/YR9K00/build/arm9_ov007.bin'
  hash: e13fa71efe4f6cf0
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: '../../../build/YR9K00/build/arm9_ov008.bin'
  hash: b4235c21e007f3e2
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: '../../../build/YR9K00/build/arm9_ov009.bin'
  hash: '05588078a1dcb083'
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: '../../../build/YR9K00/build/arm9_ov010.bin'
  hash: '7a3f18ebb2208d1b'
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: '../../../build/YR9K00/build/arm9_ov011.bin'
  hash: '70f48195bf035746'
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
- id: 12
  name: ov012
  object: '../../../build/YR9K00/build/arm9_ov012.bin'
  hash: '8f2e57bc5230e34a'
  delinks: overlays/ov012/delinks.txt
  symbols: overlays/ov012/symbols.txt
  relocations: overlays/ov012/relocs.txt
- id: 13
  name: ov013
  object: '../../../build/YR9K00/build/arm9_ov013.bin'
  hash: fbbbd5406a6b62b1
  delinks: overlays/ov013/delinks.txt
  symbols: overlays/ov013/symbols.txt
  relocations: overlays/ov013/relocs.txt
- id: 14
  name: ov014
  object: '../../../build/YR9K00/build/arm9_ov014.bin'
  hash: '5e53c1de46e1d866'
  delinks: overlays/ov014/delinks.txt
  symbols: overlays/ov014/symbols.txt
  relocations: overlays/ov014/relocs.txt
- id: 15
  name: ov015
  object: '../../../build/YR9K00/build/arm9_ov015.bin'
  hash: d402ecd6572e01cf
  delinks: overlays/ov015/delinks.txt
  symbols: overlays/ov015/symbols.txt
  relocations: overlays/ov015/relocs.txt
- id: 16
  name: ov016
  object: '../../../build/YR9K00/build/arm9_ov016.bin'
  hash: '65e63402e6802881'
  delinks: overlays/ov016/delinks.txt
  symbols: overlays/ov016/symbols.txt
  relocations: overlays/ov016/relocs.txt
- id: 17
  name: ov017
  object: '../../../build/YR9K00/build/arm9_ov017.bin'
  hash: cfa971d3f5c6218c
  delinks: overlays/ov017/delinks.txt
  symbols: overlays/ov017/symbols.txt
  relocations: overlays/ov017/relocs.txt
- id: 18
  name: ov018
  object: '../../../build/YR9K00/build/arm9_ov018.bin'
  hash: '229d33af8787be3a'
  delinks: overlays/ov018/delinks.txt
  symbols: overlays/ov018/symbols.txt
  relocations: overlays/ov018/relocs.txt
- id: 19
  name: ov019
  object: '../../../build/YR9K00/build/arm9_ov019.bin'
  hash: a53e0fdd13110899
  delinks: overlays/ov019/delinks.txt
  symbols: overlays/ov019/symbols.txt
  relocations: overlays/ov019/relocs.txt
- id: 20
  name: ov020
  object: '../../../build/YR9K00/build/arm9_ov020.bin'
  hash: '415d9612bb095f2c'
  delinks: overlays/ov020/delinks.txt
  symbols: overlays/ov020/symbols.txt
  relocations: overlays/ov020/relocs.txt
- id: 21
  name: ov021
  object: '../../../build/YR9K00/build/arm9_ov021.bin'
  hash: '7e8b4e7d8d2ff269'
  delinks: overlays/ov021/delinks.txt
  symbols: overlays/ov021/symbols.txt
  relocations: overlays/ov021/relocs.txt
- id: 22
  name: ov022
  object: '../../../build/YR9K00/build/arm9_ov022.bin'
  hash: '59fccf6be1d475ec'
  delinks: overlays/ov022/delinks.txt
  symbols: overlays/ov022/symbols.txt
  relocations: overlays/ov022/relocs.txt
- id: 23
  name: ov023
  object: '../../../build/YR9K00/build/arm9_ov023.bin'
  hash: ab9ad3e5332ca97f
  delinks: overlays/ov023/delinks.txt
  symbols: overlays/ov023/symbols.txt
  relocations: overlays/ov023/relocs.txt
- id: 24
  name: ov024
  object: '../../../build/YR9K00/build/arm9_ov024.bin'
  hash: '279880264d4dacac'
  delinks: overlays/ov024/delinks.txt
  symbols: overlays/ov024/symbols.txt
  relocations: overlays/ov024/relocs.txt
- id: 25
  name: ov025
  object: '../../../build/YR9K00/build/arm9_ov025.bin'
  hash: c14e347eb1f86a74
  delinks: overlays/ov025/delinks.txt
  symbols: overlays/ov025/symbols.txt
  relocations: overlays/ov025/relocs.txt
- id: 26
  name: ov026
  object: '../../../build/YR9K00/build/arm9_ov026.bin'
  hash: '65d022b6467806a8'
  delinks: overlays/ov026/delinks.txt
  symbols: overlays/ov026/symbols.txt
  relocations: overlays/ov026/relocs.txt
- id: 27
  name: ov027
  object: '../../../build/YR9K00/build/arm9_ov027.bin'
  hash: b777c30781db62b1
  delinks: overlays/ov027/delinks.txt
  symbols: overlays/ov027/symbols.txt
  relocations: overlays/ov027/relocs.txt
- id: 28
  name: ov028
  object: '../../../build/YR9K00/build/arm9_ov028.bin'
  hash: '83d01e4e0a1a3867'
  delinks: overlays/ov028/delinks.txt
  symbols: overlays/ov028/symbols.txt
  relocations: overlays/ov028/relocs.txt
- id: 29
  name: ov029
  object: '../../../build/YR9K00/build/arm9_ov029.bin'
  hash: '3c1f9dd65551fff7'
  delinks: overlays/ov029/delinks.txt
  symbols: overlays/ov029/symbols.txt
  relocations: overlays/ov029/relocs.txt
- id: 30
  name: ov030
  object: '../../../build/YR9K00/build/arm9_ov030.bin'
  hash: dedfe34d728f5174
  delinks: overlays/ov030/delinks.txt
  symbols: overlays/ov030/symbols.txt
  relocations: overlays/ov030/relocs.txt
- id: 31
  name: ov031
  object: '../../../build/YR9K00/build/arm9_ov031.bin'
  hash: bf98b0bffb36bb68
  delinks: overlays/ov031/delinks.txt
  symbols: overlays/ov031/symbols.txt
  relocations: overlays/ov031/relocs.txt
- id: 32
  name: ov032
  object: '../../../build/YR9K00/build/arm9_ov032.bin'
  hash: '4da762d312c2b4ef'
  delinks: overlays/ov032/delinks.txt
  symbols: overlays/ov032/symbols.txt
  relocations: overlays/ov032/relocs.txt
- id: 33
  name: ov033
  object: '../../../build/YR9K00/build/arm9_ov033.bin'
  hash: '6255d145832b14c7'
  delinks: overlays/ov033/delinks.txt
  symbols: overlays/ov033/symbols.txt
  relocations: overlays/ov033/relocs.txt
- id: 34
  name: ov034
  object: '../../../build/YR9K00/build/arm9_ov034.bin'
  hash: '79b0fece959d678f'
  delinks: overlays/ov034/delinks.txt
  symbols: overlays/ov034/symbols.txt
  relocations: overlays/ov034/relocs.txt
- id: 35
  name: ov035
  object: '../../../build/YR9K00/build/arm9_ov035.bin'
  hash: '65f631662826c3fe'
  delinks: overlays/ov035/delinks.txt
  symbols: overlays/ov035/symbols.txt
  relocations: overlays/ov035/relocs.txt
- id: 36
  name: ov036
  object: '../../../build/YR9K00/build/arm9_ov036.bin'
  hash: '0acef3ba9bbcaa33'
  delinks: overlays/ov036/delinks.txt
  symbols: overlays/ov036/symbols.txt
  relocations: overlays/ov036/relocs.txt
- id: 37
  name: ov037
  object: '../../../build/YR9K00/build/arm9_ov037.bin'
  hash: '31dbd6288fadd4b5'
  delinks: overlays/ov037/delinks.txt
  symbols: overlays/ov037/symbols.txt
  relocations: overlays/ov037/relocs.txt
- id: 38
  name: ov038
  object: '../../../build/YR9K00/build/arm9_ov038.bin'
  hash: '5b25e66521b6ede8'
  delinks: overlays/ov038/delinks.txt
  symbols: overlays/ov038/symbols.txt
  relocations: overlays/ov038/relocs.txt
- id: 39
  name: ov039
  object: '../../../build/YR9K00/build/arm9_ov039.bin'
  hash: '32c432f886393b4c'
  delinks: overlays/ov039/delinks.txt
  symbols: overlays/ov039/symbols.txt
  relocations: overlays/ov039/relocs.txt
- id: 40
  name: ov040
  object: '../../../build/YR9K00/build/arm9_ov040.bin'
  hash: '3f62bae7ef776e2d'
  delinks: overlays/ov040/delinks.txt
  symbols: overlays/ov040/symbols.txt
  relocations: overlays/ov040/relocs.txt
- id: 41
  name: ov041
  object: '../../../build/YR9K00/build/arm9_ov041.bin'
  hash: '0522c75def057433'
  delinks: overlays/ov041/delinks.txt
  symbols: overlays/ov041/symbols.txt
  relocations: overlays/ov041/relocs.txt
- id: 42
  name: ov042
  object: '../../../build/YR9K00/build/arm9_ov042.bin'
  hash: '7e31f73352369e64'
  delinks: overlays/ov042/delinks.txt
  symbols: overlays/ov042/symbols.txt
  relocations: overlays/ov042/relocs.txt
- id: 43
  name: ov043
  object: '../../../build/YR9K00/build/arm9_ov043.bin'
  hash: '8441408c0a73e9f6'
  delinks: overlays/ov043/delinks.txt
  symbols: overlays/ov043/symbols.txt
  relocations: overlays/ov043/relocs.txt
- id: 44
  name: ov044
  object: '../../../build/YR9K00/build/arm9_ov044.bin'
  hash: '83b0c77f5be52a67'
  delinks: overlays/ov044/delinks.txt
  symbols: overlays/ov044/symbols.txt
  relocations: overlays/ov044/relocs.txt
- id: 45
  name: ov045
  object: '../../../build/YR9K00/build/arm9_ov045.bin'
  hash: e3af864b0c482e52
  delinks: overlays/ov045/delinks.txt
  symbols: overlays/ov045/symbols.txt
  relocations: overlays/ov045/relocs.txt
- id: 46
  name: ov046
  object: '../../../build/YR9K00/build/arm9_ov046.bin'
  hash: '0e6dd1b7fdcb97b6'
  delinks: overlays/ov046/delinks.txt
  symbols: overlays/ov046/symbols.txt
  relocations: overlays/ov046/relocs.txt
- id: 47
  name: ov047
  object: '../../../build/YR9K00/build/arm9_ov047.bin'
  hash: '70f642e15fa7701b'
  delinks: overlays/ov047/delinks.txt
  symbols: overlays/ov047/symbols.txt
  relocations: overlays/ov047/relocs.txt
- id: 48
  name: ov048
  object: '../../../build/YR9K00/build/arm9_ov048.bin'
  hash: f7493e507f81706f
  delinks: overlays/ov048/delinks.txt
  symbols: overlays/ov048/symbols.txt
  relocations: overlays/ov048/relocs.txt
- id: 49
  name: ov049
  object: '../../../build/YR9K00/build/arm9_ov049.bin'
  hash: '0aad022d9aaaa96d'
  delinks: overlays/ov049/delinks.txt
  symbols: overlays/ov049/symbols.txt
  relocations: overlays/ov049/relocs.txt
- id: 50
  name: ov050
  object: '../../../build/YR9K00/build/arm9_ov050.bin'
  hash: '99708f44abc0a7a8'
  delinks: overlays/ov050/delinks.txt
  symbols: overlays/ov050/symbols.txt
  relocations: overlays/ov050/relocs.txt
- id: 51
  name: ov051
  object: '../../../build/YR9K00/build/arm9_ov051.bin'
  hash: dbb9bb19b042111e
  delinks: overlays/ov051/delinks.txt
  symbols: overlays/ov051/symbols.txt
  relocations: overlays/ov051/relocs.txt
- id: 52
  name: ov052
  object: '../../../build/YR9K00/build/arm9_ov052.bin'
  hash: '4a83d07452984c0b'
  delinks: overlays/ov052/delinks.txt
  symbols: overlays/ov052/symbols.txt
  relocations: overlays/ov052/relocs.txt
- id: 53
  name: ov053
  object: '../../../build/YR9K00/build/arm9_ov053.bin'
  hash: '3a4c25d9b1653f0a'
  delinks: overlays/ov053/delinks.txt
  symbols: overlays/ov053/symbols.txt
  relocations: overlays/ov053/relocs.txt
- id: 54
  name: ov054
  object: '../../../build/YR9K00/build/arm9_ov054.bin'
  hash: '0c0a9cb35592c2be'
  delinks: overlays/ov054/delinks.txt
  symbols: overlays/ov054/symbols.txt
  relocations: overlays/ov054/relocs.txt
- id: 55
  name: ov055
  object: '../../../build/YR9K00/build/arm9_ov055.bin'
  hash: '40a6c0f583069ebd'
  delinks: overlays/ov055/delinks.txt
  symbols: overlays/ov055/symbols.txt
  relocations: overlays/ov055/relocs.txt
- id: 56
  name: ov056
  object: '../../../build/YR9K00/build/arm9_ov056.bin'
  hash: '8598bdd500d067af'
  delinks: overlays/ov056/delinks.txt
  symbols: overlays/ov056/symbols.txt
  relocations: overlays/ov056/relocs.txt
- id: 57
  name: ov057
  object: '../../../build/YR9K00/build/arm9_ov057.bin'
  hash: '7b8073c3e9d675be'
  delinks: overlays/ov057/delinks.txt
  symbols: overlays/ov057/symbols.txt
  relocations: overlays/ov057/relocs.txt
- id: 58
  name: ov058
  object: '../../../build/YR9K00/build/arm9_ov058.bin'
  hash: '06c90b3e2eca8f54'
  delinks: overlays/ov058/delinks.txt
  symbols: overlays/ov058/symbols.txt
  relocations: overlays/ov058/relocs.txt
- id: 59
  name: ov059
  object: '../../../build/YR9K00/build/arm9_ov059.bin'
  hash: '7c351cba6d0bffbd'
  delinks: overlays/ov059/delinks.txt
  symbols: overlays/ov059/symbols.txt
  relocations: overlays/ov059/relocs.txt
- id: 60
  name: ov060
  object: '../../../build/YR9K00/build/arm9_ov060.bin'
  hash: ad9ce400160b3ed9
  delinks: overlays/ov060/delinks.txt
  symbols: overlays/ov060/symbols.txt
  relocations: overlays/ov060/relocs.txt
- id: 61
  name: ov061
  object: '../../../build/YR9K00/build/arm9_ov061.bin'
  hash: '67a224f37a3a9998'
  delinks: overlays/ov061/delinks.txt
  symbols: overlays/ov061/symbols.txt
  relocations: overlays/ov061/relocs.txt
- id: 62
  name: ov062
  object: '../../../build/YR9K00/build/arm9_ov062.bin'
  hash: '9e70f96c9d24fdb5'
  delinks: overlays/ov062/delinks.txt
  symbols: overlays/ov062/symbols.txt
  relocations: overlays/ov062/relocs.txt
- id: 63
  name: ov063
  object: '../../../build/YR9K00/build/arm9_ov063.bin'
  hash: '2c3f9e6aa96676f7'
  delinks: overlays/ov063/delinks.txt
  symbols: overlays/ov063/symbols.txt
  relocations: overlays/ov063/relocs.txt
- id: 64
  name: ov064
  object: '../../../build/YR9K00/build/arm9_ov064.bin'
  hash: '57b8bbd54e8af3ad'
  delinks: overlays/ov064/delinks.txt
  symbols: overlays/ov064/symbols.txt
  relocations: overlays/ov064/relocs.txt
- id: 65
  name: ov065
  object: '../../../build/YR9K00/build/arm9_ov065.bin'
  hash: f0c9d3dcf1b0fa36
  delinks: overlays/ov065/delinks.txt
  symbols: overlays/ov065/symbols.txt
  relocations: overlays/ov065/relocs.txt
- id: 66
  name: ov066
  object: '../../../build/YR9K00/build/arm9_ov066.bin'
  hash: '3846f693ccb00a08'
  delinks: overlays/ov066/delinks.txt
  symbols: overlays/ov066/symbols.txt
  relocations: overlays/ov066/relocs.txt
- id: 67
  name: ov067
  object: '../../../build/YR9K00/build/arm9_ov067.bin'
  hash: f81c3a5c1eb74ea6
  delinks: overlays/ov067/delinks.txt
  symbols: overlays/ov067/symbols.txt
  relocations: overlays/ov067/relocs.txt
- id: 68
  name: ov068
  object: '../../../build/YR9K00/build/arm9_ov068.bin'
  hash: d5c290ba2a4b72b3
  delinks: overlays/ov068/delinks.txt
  symbols: overlays/ov068/symbols.txt
  relocations: overlays/ov068/relocs.txt
- id: 69
  name: ov069
  object: '../../../build/YR9K00/build/arm9_ov069.bin'
  hash: '542f5f97420b53d1'
  delinks: overlays/ov069/delinks.txt
  symbols: overlays/ov069/symbols.txt
  relocations: overlays/ov069/relocs.txt
- id: 70
  name: ov070
  object: '../../../build/YR9K00/build/arm9_ov070.bin'
  hash: f9c8410c1843e686
  delinks: overlays/ov070/delinks.txt
  symbols: overlays/ov070/symbols.txt
  relocations: overlays/ov070/relocs.txt
- id: 71
  name: ov071
  object: '../../../build/YR9K00/build/arm9_ov071.bin'
  hash: a61701906b000ecb
  delinks: overlays/ov071/delinks.txt
  symbols: overlays/ov071/symbols.txt
  relocations: overlays/ov071/relocs.txt
- id: 72
  name: ov072
  object: '../../../build/YR9K00/build/arm9_ov072.bin'
  hash: '2e3041b947356168'
  delinks: overlays/ov072/delinks.txt
  symbols: overlays/ov072/symbols.txt
  relocations: overlays/ov072/relocs.txt
- id: 73
  name: ov073
  object: '../../../build/YR9K00/build/arm9_ov073.bin'
  hash: '5d2d04e624be8fe2'
  delinks: overlays/ov073/delinks.txt
  symbols: overlays/ov073/symbols.txt
  relocations: overlays/ov073/relocs.txt
- id: 74
  name: ov074
  object: '../../../build/YR9K00/build/arm9_ov074.bin'
  hash: '3ebff4fa0c101a56'
  delinks: overlays/ov074/delinks.txt
  symbols: overlays/ov074/symbols.txt
  relocations: overlays/ov074/relocs.txt
- id: 75
  name: ov075
  object: '../../../build/YR9K00/build/arm9_ov075.bin'
  hash: '4c465cf289d8d40a'
  delinks: overlays/ov075/delinks.txt
  symbols: overlays/ov075/symbols.txt
  relocations: overlays/ov075/relocs.txt
- id: 76
  name: ov076
  object: '../../../build/YR9K00/build/arm9_ov076.bin'
  hash: edffd4d72ad401e5
  delinks: overlays/ov076/delinks.txt
  symbols: overlays/ov076/symbols.txt
  relocations: overlays/ov076/relocs.txt
- id: 77
  name: ov077
  object: '../../../build/YR9K00/build/arm9_ov077.bin'
  hash: '47d33943c4e01b20'
  delinks: overlays/ov077/delinks.txt
  symbols: overlays/ov077/symbols.txt
  relocations: overlays/ov077/relocs.txt
- id: 78
  name: ov078
  object: '../../../build/YR9K00/build/arm9_ov078.bin'
  hash: '601076b042ce5f17'
  delinks: overlays/ov078/delinks.txt
  symbols: overlays/ov078/symbols.txt
  relocations: overlays/ov078/relocs.txt
- id: 79
  name: ov079
  object: '../../../build/YR9K00/build/arm9_ov079.bin'
  hash: '842af96965e3a2da'
  delinks: overlays/ov079/delinks.txt
  symbols: overlays/ov079/symbols.txt
  relocations: overlays/ov079/relocs.txt
- id: 80
  name: ov080
  object: '../../../build/YR9K00/build/arm9_ov080.bin'
  hash: '573b776830e3b4bf'
  delinks: overlays/ov080/delinks.txt
  symbols: overlays/ov080/symbols.txt
  relocations: overlays/ov080/relocs.txt
- id: 81
  name: ov081
  object: '../../../build/YR9K00/build/arm9_ov081.bin'
  hash: c3720c45363d81b8
  delinks: overlays/ov081/delinks.txt
  symbols: overlays/ov081/symbols.txt
  relocations: overlays/ov081/relocs.txt
- id: 82
  name: ov082
  object: '../../../build/YR9K00/build/arm9_ov082.bin'
  hash: '9ccf6ec226a17d37'
  delinks: overlays/ov082/delinks.txt
  symbols: overlays/ov082/symbols.txt
  relocations: overlays/ov082/relocs.txt
- id: 83
  name: ov083
  object: '../../../build/YR9K00/build/arm9_ov083.bin'
  hash: cb726d64d7dc02a3
  delinks: overlays/ov083/delinks.txt
  symbols: overlays/ov083/symbols.txt
  relocations: overlays/ov083/relocs.txt
- id: 84
  name: ov084
  object: '../../../build/YR9K00/build/arm9_ov084.bin'
  hash: abd56d9b1d6eb934
  delinks: overlays/ov084/delinks.txt
  symbols: overlays/ov084/symbols.txt
  relocations: overlays/ov084/relocs.txt
