rom_config: '../../../orig/YR9J00/config.yaml'
build_path: '../../../build/YR9J00'
delinks_path: '../../../build/YR9J00/delinks'
main_module:
  name: main
  object: '../../../build/YR9J00/build/arm9.bin'
  hash: a80feb53ba6f576d
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../../build/YR9J00/build/itcm.bin'
  hash: d5458189877da7bb
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../../build/YR9J00/build/dtcm.bin'
  hash: '146ae500bc37c77e'
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: '../../../build/YR9J00/build/arm9_ov000.bin'
  hash: '323984b059bc5f2a'
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: '../../../build/YR9J00/build/arm9_ov001.bin'
  hash: d162858817af7d0e
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: '../../../build/YR9J00/build/arm9_ov002.bin'
  hash: '6dad602be9743a23'
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: '../../../build/YR9J00/build/arm9_ov003.bin'
  hash: '9b416e20c51b9d06'
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: '../../../build/YR9J00/build/arm9_ov004.bin'
  hash: '50b68bbdc6c861d5'
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: '../../../build/YR9J00/build/arm9_ov005.bin'
  hash: '22c00fbace80013d'
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: '../../../build/YR9J00/build/arm9_ov006.bin'
  hash: '8d3241071b051fc3'
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: '../../../build/YR9J00/build/arm9_ov007.bin'
  hash: e13fa71efe4f6cf0
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: '../../../build/YR9J00/build/arm9_ov008.bin'
  hash: b4235c21e007f3e2
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: '../../../build/YR9J00/build/arm9_ov009.bin'
  hash: '05588078a1dcb083'
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: '../../../build/YR9J00/build/arm9_ov010.bin'
  hash: '7a3f18ebb2208d1b'
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: '../../../build/YR9J00/build/arm9_ov011.bin'
  hash: '70f48195bf035746'
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
- id: 12
  name: ov012
  object: '../../../build/YR9J00/build/arm9_ov012.bin'
  hash: '8f2e57bc5230e34a'
  delinks: overlays/ov012/delinks.txt
  symbols: overlays/ov012/symbols.txt
  relocations: overlays/ov012/relocs.txt
- id: 13
  name: ov013
  object: '../../../build/YR9J00/build/arm9_ov013.bin'
  hash: fbbbd5406a6b62b1
  delinks: overlays/ov013/delinks.txt
  symbols: overlays/ov013/symbols.txt
  relocations: overlays/ov013/relocs.txt
- id: 14
  name: ov014
  object: '../../../build/YR9J00/build/arm9_ov014.bin'
  hash: '5e53c1de46e1d866'
  delinks: overlays/ov014/delinks.txt
  symbols: overlays/ov014/symbols.txt
  relocations: overlays/ov014/relocs.txt
- id: 15
  name: ov015
  object: '../../../build/YR9J00/build/arm9_ov015.bin'
  hash: d402ecd6572e01cf
  delinks: overlays/ov015/delinks.txt
  symbols: overlays/ov015/symbols.txt
  relocations: overlays/ov015/relocs.txt
- id: 16
  name: ov016
  object: '../../../build/YR9J00/build/arm9_ov016.bin'
  hash: '65e63402e6802881'
  delinks: overlays/ov016/delinks.txt
  symbols: overlays/ov016/symbols.txt
  relocations: overlays/ov016/relocs.txt
- id: 17
  name: ov017
  object: '../../../build/YR9J00/build/arm9_ov017.bin'
  hash: cfa971d3f5c6218c
  delinks: overlays/ov017/delinks.txt
  symbols: overlays/ov017/symbols.txt
  relocations: overlays/ov017/relocs.txt
- id: 18
  name: ov018
  object: '../../../build/YR9J00/build/arm9_ov018.bin'
  hash: '5495706c0a52d6f5'
  delinks: overlays/ov018/delinks.txt
  symbols: overlays/ov018/symbols.txt
  relocations: overlays/ov018/relocs.txt
- id: 19
  name: ov019
  object: '../../../build/YR9J00/build/arm9_ov019.bin'
  hash: '9ad1b8f1be536f0e'
  delinks: overlays/ov019/delinks.txt
  symbols: overlays/ov019/symbols.txt
  relocations: overlays/ov019/relocs.txt
- id: 20
  name: ov020
  object: '../../../build/YR9J00/build/arm9_ov020.bin'
  hash: '64b5976763ad8903'
  delinks: overlays/ov020/delinks.txt
  symbols: overlays/ov020/symbols.txt
  relocations: overlays/ov020/relocs.txt
- id: 21
  name: ov021
  object: '../../../build/YR9J00/build/arm9_ov021.bin'
  hash: c8309e0b099f3893
  delinks: overlays/ov021/delinks.txt
  symbols: overlays/ov021/symbols.txt
  relocations: overlays/ov021/relocs.txt
- id: 22
  name: ov022
  object: '../../../build/YR9J00/build/arm9_ov022.bin'
  hash: '5a680036884bc809'
  delinks: overlays/ov022/delinks.txt
  symbols: overlays/ov022/symbols.txt
  relocations: overlays/ov022/relocs.txt
- id: 23
  name: ov023
  object: '../../../build/YR9J00/build/arm9_ov023.bin'
  hash: f3bba628ab0e0730
  delinks: overlays/ov023/delinks.txt
  symbols: overlays/ov023/symbols.txt
  relocations: overlays/ov023/relocs.txt
- id: 24
  name: ov024
  object: '../../../build/YR9J00/build/arm9_ov024.bin'
  hash: c350048767a78c2f
  delinks: overlays/ov024/delinks.txt
  symbols: overlays/ov024/symbols.txt
  relocations: overlays/ov024/relocs.txt
- id: 25
  name: ov025
  object: '../../../build/YR9J00/build/arm9_ov025.bin'
  hash: '5480001e35af85f3'
  delinks: overlays/ov025/delinks.txt
  symbols: overlays/ov025/symbols.txt
  relocations: overlays/ov025/relocs.txt
- id: 26
  name: ov026
  object: '../../../build/YR9J00/build/arm9_ov026.bin'
  hash: '491b484749be49f3'
  delinks: overlays/ov026/delinks.txt
  symbols: overlays/ov026/symbols.txt
  relocations: overlays/ov026/relocs.txt
- id: 27
  name: ov027
  object: '../../../build/YR9J00/build/arm9_ov027.bin'
  hash: '7e2f0aff010c85a6'
  delinks: overlays/ov027/delinks.txt
  symbols: overlays/ov027/symbols.txt
  relocations: overlays/ov027/relocs.txt
- id: 28
  name: ov028
  object: '../../../build/YR9J00/build/arm9_ov028.bin'
  hash: '7b6087521e593d1c'
  delinks: overlays/ov028/delinks.txt
  symbols: overlays/ov028/symbols.txt
  relocations: overlays/ov028/relocs.txt
- id: 29
  name: ov029
  object: '../../../build/YR9J00/build/arm9_ov029.bin'
  hash: bacfce70f9ca133b
  delinks: overlays/ov029/delinks.txt
  symbols: overlays/ov029/symbols.txt
  relocations: overlays/ov029/relocs.txt
- id: 30
  name: ov030
  object: '../../../build/YR9J00/build/arm9_ov030.bin'
  hash: '6986f1b69e96fba5'
  delinks: overlays/ov030/delinks.txt
  symbols: overlays/ov030/symbols.txt
  relocations: overlays/ov030/relocs.txt
- id: 31
  name: ov031
  object: '../../../build/YR9J00/build/arm9_ov031.bin'
  hash: '5856d59eb01628d9'
  delinks: overlays/ov031/delinks.txt
  symbols: overlays/ov031/symbols.txt
  relocations: overlays/ov031/relocs.txt
- id: 32
  name: ov032
  object: '../../../build/YR9J00/build/arm9_ov032.bin'
  hash: '889027809702e273'
  delinks: overlays/ov032/delinks.txt
  symbols: overlays/ov032/symbols.txt
  relocations: overlays/ov032/relocs.txt
- id: 33
  name: ov033
  object: '../../../build/YR9J00/build/arm9_ov033.bin'
  hash: '50ab18cc84a8b88f'
  delinks: overlays/ov033/delinks.txt
  symbols: overlays/ov033/symbols.txt
  relocations: overlays/ov033/relocs.txt
- id: 34
  name: ov034
  object: '../../../build/YR9J00/build/arm9_ov034.bin'
  hash: f382d89d52f854db
  delinks: overlays/ov034/delinks.txt
  symbols: overlays/ov034/symbols.txt
  relocations: overlays/ov034/relocs.txt
- id: 35
  name: ov035
  object: '../../../build/YR9J00/build/arm9_ov035.bin'
  hash: '40be402ac6031db5'
  delinks: overlays/ov035/delinks.txt
  symbols: overlays/ov035/symbols.txt
  relocations: overlays/ov035/relocs.txt
- id: 36
  name: ov036
  object: '../../../build/YR9J00/build/arm9_ov036.bin'
  hash: '45b597dcc8e5e789'
  delinks: overlays/ov036/delinks.txt
  symbols: overlays/ov036/symbols.txt
  relocations: overlays/ov036/relocs.txt
- id: 37
  name: ov037
  object: '../../../build/YR9J00/build/arm9_ov037.bin'
  hash: ef5d71da6aed5d79
  delinks: overlays/ov037/delinks.txt
  symbols: overlays/ov037/symbols.txt
  relocations: overlays/ov037/relocs.txt
- id: 38
  name: ov038
  object: '../../../build/YR9J00/build/arm9_ov038.bin'
  hash: d62c9688d4580556
  delinks: overlays/ov038/delinks.txt
  symbols: overlays/ov038/symbols.txt
  relocations: overlays/ov038/relocs.txt
- id: 39
  name: ov039
  object: '../../../build/YR9J00/build/arm9_ov039.bin'
  hash: '501f6a7eb884093d'
  delinks: overlays/ov039/delinks.txt
  symbols: overlays/ov039/symbols.txt
  relocations: overlays/ov039/relocs.txt
- id: 40
  name: ov040
  object: '../../../build/YR9J00/build/arm9_ov040.bin'
  hash: '7ac0a79303e247c3'
  delinks: overlays/ov040/delinks.txt
  symbols: overlays/ov040/symbols.txt
  relocations: overlays/ov040/relocs.txt
- id: 41
  name: ov041
  object: '../../../build/YR9J00/build/arm9_ov041.bin'
  hash: d289ddb05b6a8dc8
  delinks: overlays/ov041/delinks.txt
  symbols: overlays/ov041/symbols.txt
  relocations: overlays/ov041/relocs.txt
- id: 42
  name: ov042
  object: '../../../build/YR9J00/build/arm9_ov042.bin'
  hash: '1c8a96bd7cb44642'
  delinks: overlays/ov042/delinks.txt
  symbols: overlays/ov042/symbols.txt
  relocations: overlays/ov042/relocs.txt
- id: 43
  name: ov043
  object: '../../../build/YR9J00/build/arm9_ov043.bin'
  hash: ba97892995c22913
  delinks: overlays/ov043/delinks.txt
  symbols: overlays/ov043/symbols.txt
  relocations: overlays/ov043/relocs.txt
- id: 44
  name: ov044
  object: '../../../build/YR9J00/build/arm9_ov044.bin'
  hash: '96be49f69351d0c2'
  delinks: overlays/ov044/delinks.txt
  symbols: overlays/ov044/symbols.txt
  relocations: overlays/ov044/relocs.txt
- id: 45
  name: ov045
  object: '../../../build/YR9J00/build/arm9_ov045.bin'
  hash: '4850bb75d327f605'
  delinks: overlays/ov045/delinks.txt
  symbols: overlays/ov045/symbols.txt
  relocations: overlays/ov045/relocs.txt
- id: 46
  name: ov046
  object: '../../../build/YR9J00/build/arm9_ov046.bin'
  hash: '897ceb9c022a2e9c'
  delinks: overlays/ov046/delinks.txt
  symbols: overlays/ov046/symbols.txt
  relocations: overlays/ov046/relocs.txt
- id: 47
  name: ov047
  object: '../../../build/YR9J00/build/arm9_ov047.bin'
  hash: fe9f42ab2427baed
  delinks: overlays/ov047/delinks.txt
  symbols: overlays/ov047/symbols.txt
  relocations: overlays/ov047/relocs.txt
- id: 48
  name: ov048
  object: '../../../build/YR9J00/build/arm9_ov048.bin'
  hash: b5ffdba743326d16
  delinks: overlays/ov048/delinks.txt
  symbols: overlays/ov048/symbols.txt
  relocations: overlays/ov048/relocs.txt
- id: 49
  name: ov049
  object: '../../../build/YR9J00/build/arm9_ov049.bin'
  hash: '318bbfa3bd2a6fa8'
  delinks: overlays/ov049/delinks.txt
  symbols: overlays/ov049/symbols.txt
  relocations: overlays/ov049/relocs.txt
- id: 50
  name: ov050
  object: '../../../build/YR9J00/build/arm9_ov050.bin'
  hash: e3fe9353a4a87e93
  delinks: overlays/ov050/delinks.txt
  symbols: overlays/ov050/symbols.txt
  relocations: overlays/ov050/relocs.txt
- id: 51
  name: ov051
  object: '../../../build/YR9J00/build/arm9_ov051.bin'
  hash: a4b34fa8e1a1b7a1
  delinks: overlays/ov051/delinks.txt
  symbols: overlays/ov051/symbols.txt
  relocations: overlays/ov051/relocs.txt
- id: 52
  name: ov052
  object: '../../../build/YR9J00/build/arm9_ov052.bin'
  hash: '3d02474a520bd253'
  delinks: overlays/ov052/delinks.txt
  symbols: overlays/ov052/symbols.txt
  relocations: overlays/ov052/relocs.txt
- id: 53
  name: ov053
  object: '../../../build/YR9J00/build/arm9_ov053.bin'
  hash: '7a9c50f19310f306'
  delinks: overlays/ov053/delinks.txt
  symbols: overlays/ov053/symbols.txt
  relocations: overlays/ov053/relocs.txt
- id: 54
  name: ov054
  object: '../../../build/YR9J00/build/arm9_ov054.bin'
  hash: '1c3e8ccdf39cb423'
  delinks: overlays/ov054/delinks.txt
  symbols: overlays/ov054/symbols.txt
  relocations: overlays/ov054/relocs.txt
- id: 55
  name: ov055
  object: '../../../build/YR9J00/build/arm9_ov055.bin'
  hash: ca6e00b93078e0fb
  delinks: overlays/ov055/delinks.txt
  symbols: overlays/ov055/symbols.txt
  relocations: overlays/ov055/relocs.txt
- id: 56
  name: ov056
  object: '../../../build/YR9J00/build/arm9_ov056.bin'
  hash: '6da3b858e1c0183e'
  delinks: overlays/ov056/delinks.txt
  symbols: overlays/ov056/symbols.txt
  relocations: overlays/ov056/relocs.txt
- id: 57
  name: ov057
  object: '../../../build/YR9J00/build/arm9_ov057.bin'
  hash: ed80adce87633fe3
  delinks: overlays/ov057/delinks.txt
  symbols: overlays/ov057/symbols.txt
  relocations: overlays/ov057/relocs.txt
- id: 58
  name: ov058
  object: '../../../build/YR9J00/build/arm9_ov058.bin'
  hash: '9497a7d302d80882'
  delinks: overlays/ov058/delinks.txt
  symbols: overlays/ov058/symbols.txt
  relocations: overlays/ov058/relocs.txt
- id: 59
  name: ov059
  object: '../../../build/YR9J00/build/arm9_ov059.bin'
  hash: a2ace32f72e47122
  delinks: overlays/ov059/delinks.txt
  symbols: overlays/ov059/symbols.txt
  relocations: overlays/ov059/relocs.txt
- id: 60
  name: ov060
  object: '../../../build/YR9J00/build/arm9_ov060.bin'
  hash: '98bc99d82ea05fbd'
  delinks: overlays/ov060/delinks.txt
  symbols: overlays/ov060/symbols.txt
  relocations: overlays/ov060/relocs.txt
- id: 61
  name: ov061
  object: '../../../build/YR9J00/build/arm9_ov061.bin'
  hash: fc4ca47a8d554c4c
  delinks: overlays/ov061/delinks.txt
  symbols: overlays/ov061/symbols.txt
  relocations: overlays/ov061/relocs.txt
- id: 62
  name: ov062
  object: '../../../build/YR9J00/build/arm9_ov062.bin'
  hash: '6b6ea8e5d3525e1f'
  delinks: overlays/ov062/delinks.txt
  symbols: overlays/ov062/symbols.txt
  relocations: overlays/ov062/relocs.txt
- id: 63
  name: ov063
  object: '../../../build/YR9J00/build/arm9_ov063.bin'
  hash: '2ae9103cd369b204'
  delinks: overlays/ov063/delinks.txt
  symbols: overlays/ov063/symbols.txt
  relocations: overlays/ov063/relocs.txt
- id: 64
  name: ov064
  object: '../../../build/YR9J00/build/arm9_ov064.bin'
  hash: ce0cd5957442eb2e
  delinks: overlays/ov064/delinks.txt
  symbols: overlays/ov064/symbols.txt
  relocations: overlays/ov064/relocs.txt
- id: 65
  name: ov065
  object: '../../../build/YR9J00/build/arm9_ov065.bin'
  hash: '8dd8dd7692d08f93'
  delinks: overlays/ov065/delinks.txt
  symbols: overlays/ov065/symbols.txt
  relocations: overlays/ov065/relocs.txt
- id: 66
  name: ov066
  object: '../../../build/YR9J00/build/arm9_ov066.bin'
  hash: abd578ce4db50a20
  delinks: overlays/ov066/delinks.txt
  symbols: overlays/ov066/symbols.txt
  relocations: overlays/ov066/relocs.txt
- id: 67
  name: ov067
  object: '../../../build/YR9J00/build/arm9_ov067.bin'
  hash: b9a673090cb1ca18
  delinks: overlays/ov067/delinks.txt
  symbols: overlays/ov067/symbols.txt
  relocations: overlays/ov067/relocs.txt
- id: 68
  name: ov068
  object: '../../../build/YR9J00/build/arm9_ov068.bin'
  hash: '8f65c027d8e8f758'
  delinks: overlays/ov068/delinks.txt
  symbols: overlays/ov068/symbols.txt
  relocations: overlays/ov068/relocs.txt
- id: 69
  name: ov069
  object: '../../../build/YR9J00/build/arm9_ov069.bin'
  hash: beba2d71e1a67a82
  delinks: overlays/ov069/delinks.txt
  symbols: overlays/ov069/symbols.txt
  relocations: overlays/ov069/relocs.txt
- id: 70
  name: ov070
  object: '../../../build/YR9J00/build/arm9_ov070.bin'
  hash: '59ea6a3f912bfb2c'
  delinks: overlays/ov070/delinks.txt
  symbols: overlays/ov070/symbols.txt
  relocations: overlays/ov070/relocs.txt
- id: 71
  name: ov071
  object: '../../../build/YR9J00/build/arm9_ov071.bin'
  hash: f5b1e1facff16719
  delinks: overlays/ov071/delinks.txt
  symbols: overlays/ov071/symbols.txt
  relocations: overlays/ov071/relocs.txt
- id: 72
  name: ov072
  object: '../../../build/YR9J00/build/arm9_ov072.bin'
  hash: '158d0f7393d549cc'
  delinks: overlays/ov072/delinks.txt
  symbols: overlays/ov072/symbols.txt
  relocations: overlays/ov072/relocs.txt
- id: 73
  name: ov073
  object: '../../../build/YR9J00/build/arm9_ov073.bin'
  hash: '92af23fb1711a636'
  delinks: overlays/ov073/delinks.txt
  symbols: overlays/ov073/symbols.txt
  relocations: overlays/ov073/relocs.txt
- id: 74
  name: ov074
  object: '../../../build/YR9J00/build/arm9_ov074.bin'
  hash: d6f203e0a3ee9148
  delinks: overlays/ov074/delinks.txt
  symbols: overlays/ov074/symbols.txt
  relocations: overlays/ov074/relocs.txt
- id: 75
  name: ov075
  object: '../../../build/YR9J00/build/arm9_ov075.bin'
  hash: '41215662accce958'
  delinks: overlays/ov075/delinks.txt
  symbols: overlays/ov075/symbols.txt
  relocations: overlays/ov075/relocs.txt
- id: 76
  name: ov076
  object: '../../../build/YR9J00/build/arm9_ov076.bin'
  hash: c0debb267f35582c
  delinks: overlays/ov076/delinks.txt
  symbols: overlays/ov076/symbols.txt
  relocations: overlays/ov076/relocs.txt
- id: 77
  name: ov077
  object: '../../../build/YR9J00/build/arm9_ov077.bin'
  hash: '43baac8b8f584161'
  delinks: overlays/ov077/delinks.txt
  symbols: overlays/ov077/symbols.txt
  relocations: overlays/ov077/relocs.txt
- id: 78
  name: ov078
  object: '../../../build/YR9J00/build/arm9_ov078.bin'
  hash: a77624cfb2b10f35
  delinks: overlays/ov078/delinks.txt
  symbols: overlays/ov078/symbols.txt
  relocations: overlays/ov078/relocs.txt
- id: 79
  name: ov079
  object: '../../../build/YR9J00/build/arm9_ov079.bin'
  hash: fdc1d8260102eec5
  delinks: overlays/ov079/delinks.txt
  symbols: overlays/ov079/symbols.txt
  relocations: overlays/ov079/relocs.txt
- id: 80
  name: ov080
  object: '../../../build/YR9J00/build/arm9_ov080.bin'
  hash: '2cb19461d1f17be8'
  delinks: overlays/ov080/delinks.txt
  symbols: overlays/ov080/symbols.txt
  relocations: overlays/ov080/relocs.txt
- id: 81
  name: ov081
  object: '../../../build/YR9J00/build/arm9_ov081.bin'
  hash: '452e5de878d2ab51'
  delinks: overlays/ov081/delinks.txt
  symbols: overlays/ov081/symbols.txt
  relocations: overlays/ov081/relocs.txt
- id: 82
  name: ov082
  object: '../../../build/YR9J00/build/arm9_ov082.bin'
  hash: ea7a4271c75c20df
  delinks: overlays/ov082/delinks.txt
  symbols: overlays/ov082/symbols.txt
  relocations: overlays/ov082/relocs.txt
- id: 83
  name: ov083
  object: '../../../build/YR9J00/build/arm9_ov083.bin'
  hash: '1066c494da6021d5'
  delinks: overlays/ov083/delinks.txt
  symbols: overlays/ov083/symbols.txt
  relocations: overlays/ov083/relocs.txt
- id: 84
  name: ov084
  object: '../../../build/YR9J00/build/arm9_ov084.bin'
  hash: dbf9433560f9c871
  delinks: overlays/ov084/delinks.txt
  symbols: overlays/ov084/symbols.txt
  relocations: overlays/ov084/relocs.txt
