name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/lagolunatic/ooe-build:main

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [YR9E00, YR9J00, YR9K00, YR9P00]

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Copy the original files to the workspace
    - name: Prepare
      run: |
        cp -R /orig .
        mv ./orig/arm7_bios.bin .

    # Build the project
    - name: Build
      run: |
        python tools/configure.py --version ${{ matrix.version }} -w wibo --compiler /mwccarm --no-extract
        ninja arm9 report check

    # Upload progress report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json
